enabled: true
titleOnly: true

# The values allowed for the "type" part of the PR title/commit message. e.g. for a PR title/commit message of "feat: add some stuff", the type would be "feat"
types:  default: feat | fix | docs | style | refactor | perf | test | build | ci | chore | revert | update
