name = "All Skyblock"
author = "mrkeww"
version = "v1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69d0f6fc5cc9ce76ffbc9732419080a928773339da33512bf8239823d8942769"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
