name = "All Skyblock"
author = "mrkeww"
version = "v1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c449070bf98394110336502ca7c6c19f948dbfad2a7fe8534addde71bde2233"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
