name = "All Skyblock"
author = "mrkeww"
version = "v1.3.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2eec32d5b5b9a68a8ceba9f872a048356c50eed3ac3dbf1659af395abc67fd1f"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
