name = "All Skyblock"
author = "jhdevv/mrkeww"
version = "v1.0.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "398a5fb15a00b1a7f81822a65ed88edcac6e9d832f17525ce75881d1a040afe4"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
