name = "All-Skyblock"
author = "mrkeww"
version = "1.4.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48914794b0a3130f65995a14fa13d18392cda9bf9661dfa4cb292da27543228d"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
