name = "All-Skyblock"
author = "mrkeww"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bafa3a9f0c072d892297c38e4197da5a5dde4cad747c7f6bc0237abfaccfdc6"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
