name = "All Skyblock"
author = "mrkeww"
version = "1.3.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3cfc9f2fb038b22ba9f7b06e862e217976c668568344a20f7d9b16f06adc340"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
