name = "All Skyblock"
author = "mrkeww"
version = "1.3.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9ee2d33179179394fa3011203644ccbfdf5bed5cf3e232fe0003f64687df329"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
