name = "All-Skyblock"
author = "mrkeww"
version = "1.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a65fae2b1c2342dfdb4b7bafdcf8c644e71c478d3f4d947a2973dfa140e593c2"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
