name = "All Skyblock"
author = "mrkeww"
version = "1.3.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d49039af6101e8846126f95683eb49364ffc3d2b79f8f5e11ff70d3d35575cc8"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
