name = "All-Skyblock"
author = "mrkeww"
version = "1.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91c0abf1569cc3fcda4e3721e31ddc841f195833e06b1708a2d5c463b9cdcc82"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
