name: Build | Workflow

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: "A release to upload modpack"
        required: true
        type: string
  workflow_call:
    inputs:
      release-tag:
        description: "A release to upload modpack"
        required: true
        type: string
jobs:
  build:
    name: Build Modpack
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check Out Git Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'

      - name: Install packwiz
        uses: supplypike/setup-bin@v3
        with:
          uri: "https://nightly.link/packwiz/packwiz/workflows/go/main/Linux%2064-bit%20x86.zip"
          name: "packwiz"
          version: "linux"

      - name: Build Modpack
        run: |
          packwiz modrinth export
          packwiz curseforge export

      - name: Upload Modpack to GitHub Releases
        run: |
          gh release upload ${{ inputs.release-tag }} ./*.{mrpack,zip} \
            --repo ${{ github.repository_owner }}/${{ github.event.repository.name }} \
            --clobber
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Modpack Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: modpack-artifacts
          path: |
            *.mrpack
            *.zip
