name: Build | Workflow

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: "A release to upload modpack"
        required: true
        type: string
      build-modrinth:
        description: "Should the Modpack .mrpack be built"
        type: string
        required: true
      build-curse:
        description: "Should the Modpack .zip be built"
        type: string
        required: true
  workflow_call:
    inputs:
      release-tag:
        description: "A release to upload modpack"
        required: true
        type: string
      build-modrinth:
        description: "Should the Modpack .mrpack be built"
        type: string
        required: true
      build-curse:
        description: "Should the Modpack .zip be built"
        type: string
        required: true
jobs:
  build:
    name: Build Modpack
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check Out Git Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'

      - name: Install packwiz
        uses: supplypike/setup-bin@v3
        with:
          uri: "https://nightly.link/packwiz/packwiz/workflows/go/main/Linux%2064-bit%20x86.zip"
          name: "packwiz"
          version: "linux"

      - name: Build Modrinth Modpack
        if: inputs.build-modrinth == 'true'
        run: |
          packwiz modrinth export

      - name: Build Curseforge Modpack
        if: inputs.build-curse == 'true'
        run: |
          packwiz curseforge export

      - name: Upload Modrinth Modpack to GitHub Releases
        if: inputs.build-modrinth == 'true'
        run: |
          gh release upload ${{ inputs.release-tag }} *.mrpack \
            --repo ${{ github.repository_owner }}/${{ github.event.repository.name }} \
            --clobber
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Curse Modpack to GitHub Releases
        if: inputs.build-curse == 'true'
        run: |
            gh release upload ${{ inputs.release-tag }} *.zip \
              --repo ${{ github.repository_owner }}/${{ github.event.repository.name }} \
              --clobber
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Modpack Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: modpack-artifacts
          path: |
            *.mrpack
            *.zip
